# Generated by Django 4.1.7 on 2023-05-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_order_status_productinorder_productinbasket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_payment',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
