# Generated by Django 4.1.7 on 2023-05-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_order_customer_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_payment',
            field=models.CharField(blank=True, choices=[('1', 'Наличными'), ('2', 'Картой')], default=None, max_length=128, null=True),
        ),
    ]
